# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        Calculadora.setObjectName("Calculadora")
        Calculadora.resize(441, 435)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Calculadora.sizePolicy().hasHeightForWidth())
        Calculadora.setSizePolicy(sizePolicy)
        Calculadora.setMinimumSize(QtCore.QSize(441, 435))
        Calculadora.setMaximumSize(QtCore.QSize(441, 435))
        self.centralWidget = QtWidgets.QWidget(Calculadora)
        self.centralWidget.setObjectName("centralWidget")
        self.gbBits = QtWidgets.QGroupBox(self.centralWidget)
        self.gbBits.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.gbBits.setTitle("")
        self.gbBits.setObjectName("gbBits")
        self.cb_00 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_00.setGeometry(QtCore.QRect(350, 125, 16, 17))
        self.cb_00.setText("")
        self.cb_00.setObjectName("cb_00")
        self.cb_01 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_01.setGeometry(QtCore.QRect(330, 125, 16, 17))
        self.cb_01.setText("")
        self.cb_01.setObjectName("cb_01")
        self.cb_02 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_02.setGeometry(QtCore.QRect(310, 125, 16, 17))
        self.cb_02.setText("")
        self.cb_02.setObjectName("cb_02")
        self.cb_03 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_03.setGeometry(QtCore.QRect(290, 125, 16, 17))
        self.cb_03.setText("")
        self.cb_03.setObjectName("cb_03")
        self.cb_04 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_04.setGeometry(QtCore.QRect(260, 125, 16, 17))
        self.cb_04.setText("")
        self.cb_04.setObjectName("cb_04")
        self.cb_05 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_05.setGeometry(QtCore.QRect(240, 125, 16, 17))
        self.cb_05.setText("")
        self.cb_05.setObjectName("cb_05")
        self.cb_06 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_06.setGeometry(QtCore.QRect(220, 125, 16, 17))
        self.cb_06.setText("")
        self.cb_06.setObjectName("cb_06")
        self.cb_07 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_07.setGeometry(QtCore.QRect(200, 125, 16, 17))
        self.cb_07.setText("")
        self.cb_07.setObjectName("cb_07")
        self.cb_08 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_08.setGeometry(QtCore.QRect(160, 125, 16, 17))
        self.cb_08.setText("")
        self.cb_08.setObjectName("cb_08")
        self.cb_09 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_09.setGeometry(QtCore.QRect(140, 125, 16, 17))
        self.cb_09.setText("")
        self.cb_09.setObjectName("cb_09")
        self.cb_10 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_10.setGeometry(QtCore.QRect(120, 125, 16, 17))
        self.cb_10.setText("")
        self.cb_10.setObjectName("cb_10")
        self.cb_11 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_11.setGeometry(QtCore.QRect(100, 125, 16, 17))
        self.cb_11.setText("")
        self.cb_11.setObjectName("cb_11")
        self.cb_12 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_12.setGeometry(QtCore.QRect(70, 125, 16, 17))
        self.cb_12.setText("")
        self.cb_12.setObjectName("cb_12")
        self.cb_13 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_13.setGeometry(QtCore.QRect(50, 125, 16, 17))
        self.cb_13.setText("")
        self.cb_13.setObjectName("cb_13")
        self.cb_14 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_14.setGeometry(QtCore.QRect(30, 125, 16, 17))
        self.cb_14.setText("")
        self.cb_14.setObjectName("cb_14")
        self.cb_15 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_15.setGeometry(QtCore.QRect(10, 125, 16, 17))
        self.cb_15.setText("")
        self.cb_15.setObjectName("cb_15")
        self.cb_16 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_16.setGeometry(QtCore.QRect(350, 85, 16, 17))
        self.cb_16.setText("")
        self.cb_16.setObjectName("cb_16")
        self.cb_17 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_17.setGeometry(QtCore.QRect(330, 85, 16, 17))
        self.cb_17.setText("")
        self.cb_17.setObjectName("cb_17")
        self.cb_18 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_18.setGeometry(QtCore.QRect(310, 85, 16, 17))
        self.cb_18.setText("")
        self.cb_18.setObjectName("cb_18")
        self.cb_19 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_19.setGeometry(QtCore.QRect(290, 85, 16, 17))
        self.cb_19.setText("")
        self.cb_19.setObjectName("cb_19")
        self.cb_20 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_20.setGeometry(QtCore.QRect(260, 85, 16, 17))
        self.cb_20.setText("")
        self.cb_20.setObjectName("cb_20")
        self.cb_21 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_21.setGeometry(QtCore.QRect(240, 85, 16, 17))
        self.cb_21.setText("")
        self.cb_21.setObjectName("cb_21")
        self.cb_22 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_22.setGeometry(QtCore.QRect(220, 85, 16, 17))
        self.cb_22.setText("")
        self.cb_22.setObjectName("cb_22")
        self.cb_23 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_23.setGeometry(QtCore.QRect(200, 85, 16, 17))
        self.cb_23.setText("")
        self.cb_23.setObjectName("cb_23")
        self.cb_24 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_24.setGeometry(QtCore.QRect(160, 85, 16, 17))
        self.cb_24.setText("")
        self.cb_24.setObjectName("cb_24")
        self.cb_25 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_25.setGeometry(QtCore.QRect(140, 85, 16, 17))
        self.cb_25.setText("")
        self.cb_25.setObjectName("cb_25")
        self.cb_26 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_26.setGeometry(QtCore.QRect(120, 85, 16, 17))
        self.cb_26.setText("")
        self.cb_26.setObjectName("cb_26")
        self.cb_27 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_27.setGeometry(QtCore.QRect(100, 85, 16, 17))
        self.cb_27.setText("")
        self.cb_27.setObjectName("cb_27")
        self.cb_28 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_28.setGeometry(QtCore.QRect(70, 85, 16, 17))
        self.cb_28.setText("")
        self.cb_28.setObjectName("cb_28")
        self.cb_29 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_29.setGeometry(QtCore.QRect(50, 85, 16, 17))
        self.cb_29.setText("")
        self.cb_29.setObjectName("cb_29")
        self.cb_30 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_30.setGeometry(QtCore.QRect(30, 85, 16, 17))
        self.cb_30.setText("")
        self.cb_30.setObjectName("cb_30")
        self.cb_31 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_31.setGeometry(QtCore.QRect(10, 85, 16, 17))
        self.cb_31.setText("")
        self.cb_31.setObjectName("cb_31")
        self.cb_32 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_32.setGeometry(QtCore.QRect(350, 45, 16, 17))
        self.cb_32.setText("")
        self.cb_32.setObjectName("cb_32")
        self.cb_33 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_33.setGeometry(QtCore.QRect(330, 45, 16, 17))
        self.cb_33.setText("")
        self.cb_33.setObjectName("cb_33")
        self.cb_34 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_34.setGeometry(QtCore.QRect(310, 45, 16, 17))
        self.cb_34.setText("")
        self.cb_34.setObjectName("cb_34")
        self.cb_35 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_35.setGeometry(QtCore.QRect(290, 45, 16, 17))
        self.cb_35.setText("")
        self.cb_35.setObjectName("cb_35")
        self.cb_36 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_36.setGeometry(QtCore.QRect(260, 45, 16, 17))
        self.cb_36.setText("")
        self.cb_36.setObjectName("cb_36")
        self.cb_37 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_37.setGeometry(QtCore.QRect(240, 45, 16, 17))
        self.cb_37.setText("")
        self.cb_37.setObjectName("cb_37")
        self.cb_38 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_38.setGeometry(QtCore.QRect(220, 45, 16, 17))
        self.cb_38.setText("")
        self.cb_38.setObjectName("cb_38")
        self.cb_39 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_39.setGeometry(QtCore.QRect(200, 45, 16, 17))
        self.cb_39.setText("")
        self.cb_39.setObjectName("cb_39")
        self.cb_40 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_40.setGeometry(QtCore.QRect(160, 45, 16, 17))
        self.cb_40.setText("")
        self.cb_40.setObjectName("cb_40")
        self.cb_41 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_41.setGeometry(QtCore.QRect(140, 45, 16, 17))
        self.cb_41.setText("")
        self.cb_41.setObjectName("cb_41")
        self.cb_42 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_42.setGeometry(QtCore.QRect(120, 45, 16, 17))
        self.cb_42.setText("")
        self.cb_42.setObjectName("cb_42")
        self.cb_43 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_43.setGeometry(QtCore.QRect(100, 45, 16, 17))
        self.cb_43.setText("")
        self.cb_43.setObjectName("cb_43")
        self.cb_44 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_44.setGeometry(QtCore.QRect(70, 45, 16, 17))
        self.cb_44.setText("")
        self.cb_44.setObjectName("cb_44")
        self.cb_45 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_45.setGeometry(QtCore.QRect(50, 45, 16, 17))
        self.cb_45.setText("")
        self.cb_45.setObjectName("cb_45")
        self.cb_46 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_46.setGeometry(QtCore.QRect(30, 45, 16, 17))
        self.cb_46.setText("")
        self.cb_46.setObjectName("cb_46")
        self.cb_47 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_47.setGeometry(QtCore.QRect(10, 45, 16, 17))
        self.cb_47.setText("")
        self.cb_47.setObjectName("cb_47")
        self.cb_48 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_48.setGeometry(QtCore.QRect(350, 5, 16, 17))
        self.cb_48.setText("")
        self.cb_48.setObjectName("cb_48")
        self.cb_49 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_49.setGeometry(QtCore.QRect(330, 5, 16, 17))
        self.cb_49.setText("")
        self.cb_49.setObjectName("cb_49")
        self.cb_50 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_50.setGeometry(QtCore.QRect(310, 5, 16, 17))
        self.cb_50.setText("")
        self.cb_50.setObjectName("cb_50")
        self.cb_51 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_51.setGeometry(QtCore.QRect(290, 5, 16, 17))
        self.cb_51.setText("")
        self.cb_51.setObjectName("cb_51")
        self.cb_52 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_52.setGeometry(QtCore.QRect(260, 5, 16, 17))
        self.cb_52.setText("")
        self.cb_52.setObjectName("cb_52")
        self.cb_53 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_53.setGeometry(QtCore.QRect(240, 5, 16, 17))
        self.cb_53.setText("")
        self.cb_53.setObjectName("cb_53")
        self.cb_54 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_54.setGeometry(QtCore.QRect(220, 5, 16, 17))
        self.cb_54.setText("")
        self.cb_54.setObjectName("cb_54")
        self.cb_55 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_55.setGeometry(QtCore.QRect(200, 5, 16, 17))
        self.cb_55.setText("")
        self.cb_55.setObjectName("cb_55")
        self.cb_56 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_56.setGeometry(QtCore.QRect(160, 5, 16, 17))
        self.cb_56.setText("")
        self.cb_56.setObjectName("cb_56")
        self.cb_57 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_57.setGeometry(QtCore.QRect(140, 5, 16, 17))
        self.cb_57.setText("")
        self.cb_57.setObjectName("cb_57")
        self.cb_58 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_58.setGeometry(QtCore.QRect(120, 5, 16, 17))
        self.cb_58.setText("")
        self.cb_58.setObjectName("cb_58")
        self.cb_59 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_59.setGeometry(QtCore.QRect(100, 5, 16, 17))
        self.cb_59.setText("")
        self.cb_59.setObjectName("cb_59")
        self.cb_60 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_60.setGeometry(QtCore.QRect(70, 5, 16, 17))
        self.cb_60.setText("")
        self.cb_60.setObjectName("cb_60")
        self.cb_61 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_61.setGeometry(QtCore.QRect(50, 5, 16, 17))
        self.cb_61.setText("")
        self.cb_61.setObjectName("cb_61")
        self.cb_62 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_62.setGeometry(QtCore.QRect(30, 5, 16, 17))
        self.cb_62.setText("")
        self.cb_62.setObjectName("cb_62")
        self.cb_63 = QtWidgets.QCheckBox(self.gbBits)
        self.cb_63.setGeometry(QtCore.QRect(10, 5, 16, 17))
        self.cb_63.setText("")
        self.cb_63.setObjectName("cb_63")
        self.label_27 = QtWidgets.QLabel(self.gbBits)
        self.label_27.setGeometry(QtCore.QRect(100, 100, 16, 16))
        self.label_27.setObjectName("label_27")
        self.label_22 = QtWidgets.QLabel(self.gbBits)
        self.label_22.setGeometry(QtCore.QRect(220, 100, 16, 16))
        self.label_22.setObjectName("label_22")
        self.label_13 = QtWidgets.QLabel(self.gbBits)
        self.label_13.setGeometry(QtCore.QRect(50, 140, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_21 = QtWidgets.QLabel(self.gbBits)
        self.label_21.setGeometry(QtCore.QRect(240, 100, 16, 16))
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(self.gbBits)
        self.label_14.setGeometry(QtCore.QRect(30, 140, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_26 = QtWidgets.QLabel(self.gbBits)
        self.label_26.setGeometry(QtCore.QRect(120, 100, 16, 16))
        self.label_26.setObjectName("label_26")
        self.label_03 = QtWidgets.QLabel(self.gbBits)
        self.label_03.setGeometry(QtCore.QRect(290, 140, 16, 16))
        self.label_03.setObjectName("label_03")
        self.label_02 = QtWidgets.QLabel(self.gbBits)
        self.label_02.setGeometry(QtCore.QRect(310, 140, 16, 16))
        self.label_02.setObjectName("label_02")
        self.label_24 = QtWidgets.QLabel(self.gbBits)
        self.label_24.setGeometry(QtCore.QRect(160, 100, 16, 16))
        self.label_24.setObjectName("label_24")
        self.label_29 = QtWidgets.QLabel(self.gbBits)
        self.label_29.setGeometry(QtCore.QRect(50, 100, 16, 16))
        self.label_29.setObjectName("label_29")
        self.label_19 = QtWidgets.QLabel(self.gbBits)
        self.label_19.setGeometry(QtCore.QRect(290, 100, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_08 = QtWidgets.QLabel(self.gbBits)
        self.label_08.setGeometry(QtCore.QRect(160, 140, 16, 16))
        self.label_08.setObjectName("label_08")
        self.label_12 = QtWidgets.QLabel(self.gbBits)
        self.label_12.setGeometry(QtCore.QRect(70, 140, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label_01 = QtWidgets.QLabel(self.gbBits)
        self.label_01.setGeometry(QtCore.QRect(330, 140, 16, 16))
        self.label_01.setObjectName("label_01")
        self.label_20 = QtWidgets.QLabel(self.gbBits)
        self.label_20.setGeometry(QtCore.QRect(260, 100, 16, 16))
        self.label_20.setObjectName("label_20")
        self.label_31 = QtWidgets.QLabel(self.gbBits)
        self.label_31.setGeometry(QtCore.QRect(10, 100, 16, 16))
        self.label_31.setObjectName("label_31")
        self.label_15 = QtWidgets.QLabel(self.gbBits)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.gbBits)
        self.label_17.setGeometry(QtCore.QRect(330, 100, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_05 = QtWidgets.QLabel(self.gbBits)
        self.label_05.setGeometry(QtCore.QRect(240, 140, 16, 16))
        self.label_05.setObjectName("label_05")
        self.label_09 = QtWidgets.QLabel(self.gbBits)
        self.label_09.setGeometry(QtCore.QRect(140, 140, 16, 16))
        self.label_09.setObjectName("label_09")
        self.label_00 = QtWidgets.QLabel(self.gbBits)
        self.label_00.setGeometry(QtCore.QRect(350, 140, 16, 16))
        self.label_00.setObjectName("label_00")
        self.label_07 = QtWidgets.QLabel(self.gbBits)
        self.label_07.setGeometry(QtCore.QRect(200, 140, 16, 16))
        self.label_07.setObjectName("label_07")
        self.label_18 = QtWidgets.QLabel(self.gbBits)
        self.label_18.setGeometry(QtCore.QRect(310, 100, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(self.gbBits)
        self.label_16.setGeometry(QtCore.QRect(350, 100, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_30 = QtWidgets.QLabel(self.gbBits)
        self.label_30.setGeometry(QtCore.QRect(30, 100, 16, 16))
        self.label_30.setObjectName("label_30")
        self.label_28 = QtWidgets.QLabel(self.gbBits)
        self.label_28.setGeometry(QtCore.QRect(70, 100, 16, 16))
        self.label_28.setObjectName("label_28")
        self.label_25 = QtWidgets.QLabel(self.gbBits)
        self.label_25.setGeometry(QtCore.QRect(140, 100, 16, 16))
        self.label_25.setObjectName("label_25")
        self.label_50 = QtWidgets.QLabel(self.gbBits)
        self.label_50.setGeometry(QtCore.QRect(310, 20, 16, 16))
        self.label_50.setObjectName("label_50")
        self.label_32 = QtWidgets.QLabel(self.gbBits)
        self.label_32.setGeometry(QtCore.QRect(350, 60, 16, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.gbBits)
        self.label_33.setGeometry(QtCore.QRect(330, 60, 16, 16))
        self.label_33.setObjectName("label_33")
        self.label_54 = QtWidgets.QLabel(self.gbBits)
        self.label_54.setGeometry(QtCore.QRect(220, 20, 16, 16))
        self.label_54.setObjectName("label_54")
        self.label_34 = QtWidgets.QLabel(self.gbBits)
        self.label_34.setGeometry(QtCore.QRect(310, 60, 16, 16))
        self.label_34.setObjectName("label_34")
        self.label_45 = QtWidgets.QLabel(self.gbBits)
        self.label_45.setGeometry(QtCore.QRect(50, 60, 16, 16))
        self.label_45.setObjectName("label_45")
        self.label_52 = QtWidgets.QLabel(self.gbBits)
        self.label_52.setGeometry(QtCore.QRect(260, 20, 16, 16))
        self.label_52.setObjectName("label_52")
        self.label_42 = QtWidgets.QLabel(self.gbBits)
        self.label_42.setGeometry(QtCore.QRect(120, 60, 16, 16))
        self.label_42.setObjectName("label_42")
        self.label_38 = QtWidgets.QLabel(self.gbBits)
        self.label_38.setGeometry(QtCore.QRect(220, 60, 16, 16))
        self.label_38.setObjectName("label_38")
        self.label_60 = QtWidgets.QLabel(self.gbBits)
        self.label_60.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.label_60.setObjectName("label_60")
        self.label_49 = QtWidgets.QLabel(self.gbBits)
        self.label_49.setGeometry(QtCore.QRect(330, 20, 16, 16))
        self.label_49.setObjectName("label_49")
        self.label_44 = QtWidgets.QLabel(self.gbBits)
        self.label_44.setGeometry(QtCore.QRect(70, 60, 16, 16))
        self.label_44.setObjectName("label_44")
        self.label_48 = QtWidgets.QLabel(self.gbBits)
        self.label_48.setGeometry(QtCore.QRect(350, 20, 16, 16))
        self.label_48.setObjectName("label_48")
        self.label_37 = QtWidgets.QLabel(self.gbBits)
        self.label_37.setGeometry(QtCore.QRect(240, 60, 16, 16))
        self.label_37.setObjectName("label_37")
        self.label_40 = QtWidgets.QLabel(self.gbBits)
        self.label_40.setGeometry(QtCore.QRect(160, 60, 16, 16))
        self.label_40.setObjectName("label_40")
        self.label_63 = QtWidgets.QLabel(self.gbBits)
        self.label_63.setGeometry(QtCore.QRect(10, 20, 16, 16))
        self.label_63.setObjectName("label_63")
        self.label_58 = QtWidgets.QLabel(self.gbBits)
        self.label_58.setGeometry(QtCore.QRect(120, 20, 16, 16))
        self.label_58.setObjectName("label_58")
        self.label_41 = QtWidgets.QLabel(self.gbBits)
        self.label_41.setGeometry(QtCore.QRect(140, 60, 16, 16))
        self.label_41.setObjectName("label_41")
        self.label_35 = QtWidgets.QLabel(self.gbBits)
        self.label_35.setGeometry(QtCore.QRect(290, 60, 16, 16))
        self.label_35.setObjectName("label_35")
        self.label_47 = QtWidgets.QLabel(self.gbBits)
        self.label_47.setEnabled(True)
        self.label_47.setGeometry(QtCore.QRect(10, 60, 16, 16))
        self.label_47.setObjectName("label_47")
        self.label_36 = QtWidgets.QLabel(self.gbBits)
        self.label_36.setGeometry(QtCore.QRect(260, 60, 16, 16))
        self.label_36.setObjectName("label_36")
        self.label_61 = QtWidgets.QLabel(self.gbBits)
        self.label_61.setGeometry(QtCore.QRect(50, 20, 16, 16))
        self.label_61.setObjectName("label_61")
        self.label_55 = QtWidgets.QLabel(self.gbBits)
        self.label_55.setGeometry(QtCore.QRect(200, 20, 16, 16))
        self.label_55.setObjectName("label_55")
        self.label_53 = QtWidgets.QLabel(self.gbBits)
        self.label_53.setGeometry(QtCore.QRect(240, 20, 16, 16))
        self.label_53.setObjectName("label_53")
        self.label_43 = QtWidgets.QLabel(self.gbBits)
        self.label_43.setGeometry(QtCore.QRect(100, 60, 16, 16))
        self.label_43.setObjectName("label_43")
        self.label_57 = QtWidgets.QLabel(self.gbBits)
        self.label_57.setGeometry(QtCore.QRect(140, 20, 16, 16))
        self.label_57.setObjectName("label_57")
        self.label_46 = QtWidgets.QLabel(self.gbBits)
        self.label_46.setGeometry(QtCore.QRect(30, 60, 16, 16))
        self.label_46.setObjectName("label_46")
        self.label_62 = QtWidgets.QLabel(self.gbBits)
        self.label_62.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.label_62.setObjectName("label_62")
        self.label_59 = QtWidgets.QLabel(self.gbBits)
        self.label_59.setGeometry(QtCore.QRect(100, 20, 16, 16))
        self.label_59.setObjectName("label_59")
        self.label_56 = QtWidgets.QLabel(self.gbBits)
        self.label_56.setGeometry(QtCore.QRect(160, 20, 16, 16))
        self.label_56.setObjectName("label_56")
        self.label_51 = QtWidgets.QLabel(self.gbBits)
        self.label_51.setGeometry(QtCore.QRect(290, 20, 16, 16))
        self.label_51.setObjectName("label_51")
        self.label_39 = QtWidgets.QLabel(self.gbBits)
        self.label_39.setGeometry(QtCore.QRect(200, 60, 16, 16))
        self.label_39.setObjectName("label_39")
        self.label_11 = QtWidgets.QLabel(self.gbBits)
        self.label_11.setGeometry(QtCore.QRect(100, 140, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.gbBits)
        self.label_10.setGeometry(QtCore.QRect(120, 140, 16, 16))
        self.label_10.setObjectName("label_10")
        self.label_04 = QtWidgets.QLabel(self.gbBits)
        self.label_04.setGeometry(QtCore.QRect(260, 140, 16, 16))
        self.label_04.setObjectName("label_04")
        self.label_23 = QtWidgets.QLabel(self.gbBits)
        self.label_23.setGeometry(QtCore.QRect(200, 100, 16, 16))
        self.label_23.setObjectName("label_23")
        self.label_06 = QtWidgets.QLabel(self.gbBits)
        self.label_06.setGeometry(QtCore.QRect(220, 140, 16, 16))
        self.label_06.setObjectName("label_06")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 160, 441, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_Hex = QtWidgets.QLabel(self.groupBox_2)
        self.label_Hex.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label_Hex.setObjectName("label_Hex")
        self.leHex = QtWidgets.QLineEdit(self.groupBox_2)
        self.leHex.setGeometry(QtCore.QRect(80, 14, 141, 20))
        self.leHex.setObjectName("leHex")
        self.label_dSig = QtWidgets.QLabel(self.groupBox_2)
        self.label_dSig.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label_dSig.setObjectName("label_dSig")
        self.leDSig = QtWidgets.QLineEdit(self.groupBox_2)
        self.leDSig.setGeometry(QtCore.QRect(80, 35, 141, 20))
        self.leDSig.setObjectName("leDSig")
        self.label_dUSig = QtWidgets.QLabel(self.groupBox_2)
        self.label_dUSig.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_dUSig.setObjectName("label_dUSig")
        self.leDUSig = QtWidgets.QLineEdit(self.groupBox_2)
        self.leDUSig.setGeometry(QtCore.QRect(80, 57, 141, 20))
        self.leDUSig.setObjectName("leDUSig")
        self.sbShift = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbShift.setGeometry(QtCore.QRect(270, 10, 42, 22))
        self.sbShift.setMinimum(1)
        self.sbShift.setMaximum(63)
        self.sbShift.setObjectName("sbShift")
        self.pbLshift = QtWidgets.QPushButton(self.groupBox_2)
        self.pbLshift.setGeometry(QtCore.QRect(240, 10, 31, 23))
        self.pbLshift.setObjectName("pbLshift")
        self.pbRshift = QtWidgets.QPushButton(self.groupBox_2)
        self.pbRshift.setGeometry(QtCore.QRect(310, 10, 31, 23))
        self.pbRshift.setObjectName("pbRshift")
        self.pbNot = QtWidgets.QPushButton(self.groupBox_2)
        self.pbNot.setGeometry(QtCore.QRect(230, 40, 31, 23))
        self.pbNot.setObjectName("pbNot")
        self.pbAnd = QtWidgets.QPushButton(self.groupBox_2)
        self.pbAnd.setGeometry(QtCore.QRect(260, 40, 31, 23))
        self.pbAnd.setObjectName("pbAnd")
        self.pbXor = QtWidgets.QPushButton(self.groupBox_2)
        self.pbXor.setGeometry(QtCore.QRect(320, 40, 31, 23))
        self.pbXor.setObjectName("pbXor")
        self.pbOr = QtWidgets.QPushButton(self.groupBox_2)
        self.pbOr.setGeometry(QtCore.QRect(290, 40, 31, 23))
        self.pbOr.setObjectName("pbOr")
        self.leBinOperator = QtWidgets.QLineEdit(self.groupBox_2)
        self.leBinOperator.setGeometry(QtCore.QRect(300, 70, 113, 20))
        self.leBinOperator.setObjectName("leBinOperator")
        self.label_68 = QtWidgets.QLabel(self.groupBox_2)
        self.label_68.setGeometry(QtCore.QRect(236, 73, 61, 16))
        self.label_68.setObjectName("label_68")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 0, 71, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.rb64 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb64.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rb64.setChecked(True)
        self.rb64.setObjectName("rb64")
        self.rb48 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb48.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.rb48.setObjectName("rb48")
        self.rb32 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb32.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rb32.setObjectName("rb32")
        self.rb16 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb16.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.rb16.setObjectName("rb16")
        self.rb8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb8.setGeometry(QtCore.QRect(10, 100, 82, 17))
        self.rb8.setObjectName("rb8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 270, 441, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.leDecS_Mat = QtWidgets.QLineEdit(self.groupBox_4)
        self.leDecS_Mat.setGeometry(QtCore.QRect(80, 41, 113, 20))
        self.leDecS_Mat.setObjectName("leDecS_Mat")
        self.label_69 = QtWidgets.QLabel(self.groupBox_4)
        self.label_69.setGeometry(QtCore.QRect(20, 46, 61, 16))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_4)
        self.label_70.setGeometry(QtCore.QRect(20, 26, 61, 16))
        self.label_70.setObjectName("label_70")
        self.leHex_Mat = QtWidgets.QLineEdit(self.groupBox_4)
        self.leHex_Mat.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.leHex_Mat.setObjectName("leHex_Mat")
        self.pbExp = QtWidgets.QPushButton(self.groupBox_4)
        self.pbExp.setGeometry(QtCore.QRect(380, 20, 31, 23))
        self.pbExp.setObjectName("pbExp")
        self.pbRest = QtWidgets.QPushButton(self.groupBox_4)
        self.pbRest.setGeometry(QtCore.QRect(310, 20, 31, 23))
        self.pbRest.setObjectName("pbRest")
        self.pbPor = QtWidgets.QPushButton(self.groupBox_4)
        self.pbPor.setGeometry(QtCore.QRect(280, 50, 31, 23))
        self.pbPor.setObjectName("pbPor")
        self.pbAdd = QtWidgets.QPushButton(self.groupBox_4)
        self.pbAdd.setGeometry(QtCore.QRect(280, 20, 31, 23))
        self.pbAdd.setObjectName("pbAdd")
        self.pbSqr = QtWidgets.QPushButton(self.groupBox_4)
        self.pbSqr.setGeometry(QtCore.QRect(380, 50, 31, 23))
        self.pbSqr.setObjectName("pbSqr")
        self.pbDiv = QtWidgets.QPushButton(self.groupBox_4)
        self.pbDiv.setGeometry(QtCore.QRect(310, 50, 31, 23))
        self.pbDiv.setObjectName("pbDiv")
        self.pbSalir = QtWidgets.QPushButton(self.centralWidget)
        self.pbSalir.setGeometry(QtCore.QRect(4, 352, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbSalir.setFont(font)
        self.pbSalir.setObjectName("pbSalir")
        Calculadora.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Calculadora)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menuBar.setObjectName("menuBar")
        Calculadora.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Calculadora)
        self.mainToolBar.setObjectName("mainToolBar")
        Calculadora.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Calculadora)
        self.statusBar.setObjectName("statusBar")
        Calculadora.setStatusBar(self.statusBar)

        self.retranslateUi(Calculadora)
        QtCore.QMetaObject.connectSlotsByName(Calculadora)

    def retranslateUi(self, Calculadora):
        _translate = QtCore.QCoreApplication.translate
        Calculadora.setWindowTitle(_translate("Calculadora", "Calculadora"))
        self.label_00.setText(_translate("Calculadora", "0"))
        self.label_01.setText(_translate("Calculadora", "1"))
        self.label_02.setText(_translate("Calculadora", "2"))
        self.label_03.setText(_translate("Calculadora", "3"))
        self.label_04.setText(_translate("Calculadora", "4"))
        self.label_05.setText(_translate("Calculadora", "5"))
        self.label_06.setText(_translate("Calculadora", "6"))
        self.label_07.setText(_translate("Calculadora", "7"))
        self.label_08.setText(_translate("Calculadora", "8"))
        self.label_09.setText(_translate("Calculadora", "9"))
        self.label_10.setText(_translate("Calculadora", "10"))
        self.label_11.setText(_translate("Calculadora", "11"))
        self.label_12.setText(_translate("Calculadora", "12"))
        self.label_13.setText(_translate("Calculadora", "13"))
        self.label_14.setText(_translate("Calculadora", "14"))
        self.label_15.setText(_translate("Calculadora", "15"))
        self.label_16.setText(_translate("Calculadora", "16"))
        self.label_17.setText(_translate("Calculadora", "17"))
        self.label_18.setText(_translate("Calculadora", "18"))
        self.label_19.setText(_translate("Calculadora", "19"))
        self.label_20.setText(_translate("Calculadora", "20"))
        self.label_21.setText(_translate("Calculadora", "21"))
        self.label_22.setText(_translate("Calculadora", "22"))
        self.label_23.setText(_translate("Calculadora", "23"))
        self.label_24.setText(_translate("Calculadora", "24"))
        self.label_25.setText(_translate("Calculadora", "25"))
        self.label_26.setText(_translate("Calculadora", "26"))
        self.label_27.setText(_translate("Calculadora", "27"))
        self.label_28.setText(_translate("Calculadora", "28"))
        self.label_29.setText(_translate("Calculadora", "29"))
        self.label_30.setText(_translate("Calculadora", "30"))
        self.label_31.setText(_translate("Calculadora", "31"))
        self.label_32.setText(_translate("Calculadora", "32"))
        self.label_33.setText(_translate("Calculadora", "33"))
        self.label_34.setText(_translate("Calculadora", "34"))
        self.label_35.setText(_translate("Calculadora", "35"))
        self.label_36.setText(_translate("Calculadora", "36"))
        self.label_37.setText(_translate("Calculadora", "37"))
        self.label_38.setText(_translate("Calculadora", "38"))
        self.label_39.setText(_translate("Calculadora", "39"))
        self.label_40.setText(_translate("Calculadora", "40"))
        self.label_41.setText(_translate("Calculadora", "41"))
        self.label_42.setText(_translate("Calculadora", "42"))
        self.label_43.setText(_translate("Calculadora", "43"))
        self.label_44.setText(_translate("Calculadora", "44"))
        self.label_45.setText(_translate("Calculadora", "45"))
        self.label_46.setText(_translate("Calculadora", "46"))
        self.label_47.setText(_translate("Calculadora", "47"))
        self.label_48.setText(_translate("Calculadora", "48"))
        self.label_49.setText(_translate("Calculadora", "49"))
        self.label_50.setText(_translate("Calculadora", "50"))
        self.label_51.setText(_translate("Calculadora", "51"))
        self.label_52.setText(_translate("Calculadora", "52"))
        self.label_53.setText(_translate("Calculadora", "53"))
        self.label_54.setText(_translate("Calculadora", "54"))
        self.label_55.setText(_translate("Calculadora", "55"))
        self.label_56.setText(_translate("Calculadora", "56"))
        self.label_57.setText(_translate("Calculadora", "57"))
        self.label_58.setText(_translate("Calculadora", "58"))
        self.label_59.setText(_translate("Calculadora", "59"))
        self.label_60.setText(_translate("Calculadora", "60"))
        self.label_61.setText(_translate("Calculadora", "61"))
        self.label_62.setText(_translate("Calculadora", "62"))
        self.label_63.setText(_translate("Calculadora", "63"))
        self.groupBox_2.setTitle(_translate("Calculadora", "Operaciones binarias"))
        self.label_Hex.setText(_translate("Calculadora", "Hexa     0x"))
        self.label_dSig.setText(_translate("Calculadora", "Decimal Sig:"))
        self.label_dUSig.setText(_translate("Calculadora", "Decimal Uns:"))
        self.pbLshift.setText(_translate("Calculadora", "<<"))
        self.pbRshift.setText(_translate("Calculadora", ">>"))
        self.pbNot.setText(_translate("Calculadora", "Not"))
        self.pbAnd.setText(_translate("Calculadora", "And"))
        self.pbXor.setText(_translate("Calculadora", "Xor"))
        self.pbOr.setText(_translate("Calculadora", "Or"))
        self.label_68.setText(_translate("Calculadora", "Operador 0x"))
        self.groupBox_3.setTitle(_translate("Calculadora", "Operar en:"))
        self.rb64.setText(_translate("Calculadora", "64 bit"))
        self.rb48.setText(_translate("Calculadora", "48 bit"))
        self.rb32.setText(_translate("Calculadora", "32 bit"))
        self.rb16.setText(_translate("Calculadora", "16 bit"))
        self.rb8.setText(_translate("Calculadora", "8 bit"))
        self.groupBox_4.setTitle(_translate("Calculadora", "Operaciones matematicas"))
        self.label_69.setText(_translate("Calculadora", "Decimal Sig:"))
        self.label_70.setText(_translate("Calculadora", "Hexa     0x"))
        self.pbExp.setText(_translate("Calculadora", "^"))
        self.pbRest.setText(_translate("Calculadora", "-"))
        self.pbPor.setText(_translate("Calculadora", "x"))
        self.pbAdd.setText(_translate("Calculadora", "+"))
        self.pbSqr.setText(_translate("Calculadora", "√"))
        self.pbDiv.setText(_translate("Calculadora", "/"))
        self.pbSalir.setText(_translate("Calculadora", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculadora = QtWidgets.QMainWindow()
    ui = Ui_Calculadora()
    ui.setupUi(Calculadora)
    Calculadora.show()
    sys.exit(app.exec_())

